apiVersion: v1
kind: Service
metadata:
  name: cassandra-headless-service
  labels:
    component: cassandra
spec:
  clusterIP: None
  selector:
    component: cassandra
  ports:
    - port: 9042
      targetPort: 9042